# Generated by Django 6.0.1 on 2026-01-24 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_requeststatuslog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="requests/attachments/%Y/%m/%d/")),
                ("file_type", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="marketplace.servicerequest",
                    ),
                ),
            ],
        ),
    ]
