# Generated by Django 5.1.2 on 2026-02-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_servicerequest_cancel_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("normal", "عادي"),
                    ("competitive", "تنافسي"),
                    ("urgent", "عاجل"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "جديد"),
                    ("sent", "أُرسل"),
                    ("accepted", "مقبول"),
                    ("in_progress", "تحت التنفيذ"),
                    ("completed", "مكتمل"),
                    ("cancelled", "ملغي"),
                    ("expired", "منتهي"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
