# Generated by Django 6.0.1 on 2026-02-18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_follow_up",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_urgent",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=80)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("basic", "الباقة الأساسية"),
                            ("leading", "الباقة الريادية"),
                            ("professional", "الباقة الاحترافية"),
                            ("extra", "الخدمات الإضافية"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "key")},
            },
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(
                fields=["user", "tier"],
                name="notificatio_user_id_ae5582_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(
                fields=["user", "key"],
                name="notificatio_user_id_757954_idx",
            ),
        ),
    ]
