# Generated by Django 6.0.1 on 2026-01-25 15:39

import apps.promo.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20, unique=True)),
                ("title", models.CharField(max_length=160)),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("banner_home", "بانر الصفحة الرئيسية"),
                            ("banner_category", "بانر صفحة القسم"),
                            ("banner_search", "بانر صفحة البحث"),
                            ("popup_home", "نافذة منبثقة رئيسية"),
                            ("popup_category", "نافذة منبثقة داخل قسم"),
                            ("featured_top5", "تمييز ضمن أول 5"),
                            ("featured_top10", "تمييز ضمن أول 10"),
                            ("boost_profile", "تعزيز ملف مقدم الخدمة"),
                            ("push_notification", "إشعار دفع (Push)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("10s", "كل 10 ثواني"),
                            ("20s", "كل 20 ثانية"),
                            ("30s", "كل 30 ثانية"),
                            ("60s", "كل 60 ثانية"),
                        ],
                        default="60s",
                        max_length=10,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("first", "الأول"),
                            ("second", "الثاني"),
                            ("top5", "ضمن أول 5"),
                            ("top10", "ضمن أول 10"),
                            ("normal", "عادي"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("target_category", models.CharField(blank=True, max_length=80)),
                ("target_city", models.CharField(blank=True, max_length=80)),
                ("redirect_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("in_review", "قيد المراجعة"),
                            ("quoted", "تم التسعير"),
                            ("pending_payment", "بانتظار الدفع"),
                            ("active", "مفعل"),
                            ("rejected", "مرفوض"),
                            ("expired", "منتهي"),
                            ("cancelled", "ملغي"),
                        ],
                        default="new",
                        max_length=25,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("total_days", models.PositiveIntegerField(default=0)),
                ("quote_note", models.CharField(blank=True, max_length=300)),
                ("reject_reason", models.CharField(blank=True, max_length=300)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promo_requests",
                        to="billing.invoice",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromoAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "صورة"),
                            ("video", "فيديو"),
                            ("pdf", "ملف PDF"),
                            ("other", "ملف إضافي"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=160)),
                (
                    "file",
                    models.FileField(
                        upload_to="promo/assets/%Y/%m/",
                        validators=[
                            apps.promo.validators.validate_file_size,
                            apps.promo.validators.validate_extension,
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="promo.promorequest",
                    ),
                ),
            ],
        ),
    ]
