# Generated by Django 6.0.1 on 2026-01-18 18:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerprofile",
            name="rating_avg",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=3
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
