# Generated by Django 6.0.1 on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0003_providerfollow_providerlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerprofile",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
