# Generated by Django 6.0.1 on 2026-02-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0007_providerprofile_completion_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="providerservice",
            new_name="providers_p_provide_935cf6_idx",
            old_name="providers_pr_provider_f3502a_idx",
        ),
    ]
