# Generated by Django 5.1.2 on 2026-02-17 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_alter_servicerequest_request_type_and_more"),
        ("messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="is_direct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="thread",
            name="participant_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direct_threads_as_p1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="participant_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direct_threads_as_p2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread",
                to="marketplace.servicerequest",
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["participant_1", "participant_2"],
                name="messaging_t_partici_d12ceb_idx",
            ),
        ),
    ]
