# Generated by Django 6.0.1 on 2026-01-25 15:32

import apps.verification.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "badge_type",
                    models.CharField(
                        choices=[("blue", "شارة زرقاء"), ("green", "شارة خضراء")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("in_review", "قيد المراجعة"),
                            ("rejected", "مرفوض"),
                            ("approved", "معتمد"),
                            ("pending_payment", "بانتظار الدفع"),
                            ("active", "مفعل"),
                            ("expired", "منتهي"),
                        ],
                        default="new",
                        max_length=25,
                    ),
                ),
                ("admin_note", models.CharField(blank=True, max_length=300)),
                ("reject_reason", models.CharField(blank=True, max_length=300)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_requests",
                        to="billing.invoice",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("id", "هوية وطنية/إقامة"),
                            ("cr", "سجل تجاري"),
                            ("iban", "آيبان/حساب بنكي"),
                            ("license", "ترخيص/تصريح"),
                            ("other", "مستند إضافي"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=160)),
                (
                    "file",
                    models.FileField(
                        upload_to="verification/docs/%Y/%m/",
                        validators=[
                            apps.verification.validators.validate_file_size,
                            apps.verification.validators.validate_extension,
                        ],
                    ),
                ),
                ("is_approved", models.BooleanField(blank=True, null=True)),
                ("decision_note", models.CharField(blank=True, max_length=300)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_doc_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="verification.verificationrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerifiedBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[("blue", "شارة زرقاء"), ("green", "شارة خضراء")],
                        max_length=20,
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="verification.verificationrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "badge_type", "is_active"],
                        name="verificatio_user_id_fcdfc6_idx",
                    )
                ],
            },
        ),
    ]
