# Generated by Django 6.0.1 on 2026-01-25 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("invoice_created", "إنشاء فاتورة"),
                            ("invoice_paid", "دفع فاتورة"),
                            ("subscription_started", "بدء اشتراك"),
                            ("subscription_active", "تفعيل اشتراك"),
                            ("verify_request_created", "طلب توثيق"),
                            ("verify_request_approved", "اعتماد توثيق"),
                            ("verify_request_rejected", "رفض توثيق"),
                            ("promo_request_created", "طلب إعلان"),
                            ("promo_request_quoted", "تسعير إعلان"),
                            ("promo_request_active", "تفعيل إعلان"),
                            ("extra_purchase_created", "شراء إضافة"),
                            ("extra_purchase_active", "تفعيل إضافة"),
                            ("login_otp_sent", "إرسال OTP"),
                            ("login_otp_verified", "تأكيد OTP"),
                        ],
                        max_length=60,
                    ),
                ),
                ("reference_type", models.CharField(blank=True, max_length=60)),
                ("reference_id", models.CharField(blank=True, max_length=60)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["action"], name="audit_audit_action_86e815_idx"
                    ),
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="audit_audit_referen_b473d9_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_audit_created_2c1626_idx"
                    ),
                ],
            },
        ),
    ]
