# Generated by Django 5.1.2 on 2026-02-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("invoice_created", "إنشاء فاتورة"),
                    ("invoice_paid", "دفع فاتورة"),
                    ("subscription_started", "بدء اشتراك"),
                    ("subscription_active", "تفعيل اشتراك"),
                    ("verify_request_created", "طلب توثيق"),
                    ("verify_request_approved", "اعتماد توثيق"),
                    ("verify_request_rejected", "رفض توثيق"),
                    ("promo_request_created", "طلب إعلان"),
                    ("promo_request_quoted", "تسعير إعلان"),
                    ("promo_request_active", "تفعيل إعلان"),
                    ("extra_purchase_created", "شراء إضافة"),
                    ("extra_purchase_active", "تفعيل إضافة"),
                    ("access_profile_updated", "تحديث صلاحيات تشغيل"),
                    ("access_profile_created", "إنشاء صلاحيات تشغيل"),
                    ("access_profile_revoked", "سحب صلاحيات تشغيل"),
                    ("access_profile_unrevoked", "إلغاء سحب صلاحيات تشغيل"),
                    ("login_otp_sent", "إرسال OTP"),
                    ("login_otp_verified", "تأكيد OTP"),
                ],
                max_length=60,
            ),
        ),
    ]
