# Generated by Django 6.0.1 on 2026-01-25 15:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20, unique=True)),
                ("title", models.CharField(default="فاتورة", max_length=160)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("currency", models.CharField(default="SAR", max_length=10)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15.00"), max_digits=5
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending", "بانتظار الدفع"),
                            ("paid", "مدفوعة"),
                            ("failed", "فشلت"),
                            ("cancelled", "ملغاة"),
                            ("refunded", "مسترجعة"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.CharField(blank=True, max_length=50)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("manual", "تحويل يدوي"), ("mock", "اختبار")],
                        default="mock",
                        max_length=30,
                    ),
                ),
                ("event_id", models.CharField(blank=True, max_length=120)),
                ("signature", models.CharField(blank=True, max_length=200)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "event_id"],
                        name="billing_web_provide_1e7620_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("manual", "تحويل يدوي"), ("mock", "اختبار")],
                        default="mock",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "بدأت"),
                            ("redirected", "تم التحويل"),
                            ("success", "ناجحة"),
                            ("failed", "فشلت"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(blank=True, max_length=80)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="SAR", max_length=10)),
                ("checkout_url", models.URLField(blank=True)),
                ("provider_reference", models.CharField(blank=True, max_length=120)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "provider_reference"],
                        name="billing_pay_provide_8c9e21_idx",
                    ),
                    models.Index(
                        fields=["idempotency_key"],
                        name="billing_pay_idempot_671de2_idx",
                    ),
                ],
            },
        ),
    ]
