# Generated by ChatGPT on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(fields=["phone", "created_at"], name="accounts_otp_phone_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(fields=["ip_address", "created_at"], name="accounts_otp_ip_created_at_idx"),
        ),
    ]
