# Generated by Django 6.0.1 on 2026-02-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_otp_ip_address_and_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="otp",
            new_name="accounts_ot_phone_463bcb_idx",
            old_name="accounts_otp_phone_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="otp",
            new_name="accounts_ot_ip_addr_ee3f9b_idx",
            old_name="accounts_otp_ip_created_at_idx",
        ),
    ]
